### ISSUE TITLE
Adding an Objective-C file to a swift plugin project will stop it from working

### ISSUE THREAD

**Issue by benrudhart** [kattrali/Xcode-Plugin-Template#32] opened 2015-03-10 08:30 UTC
After creating a new swift xcode plugin everything works out fine.
As soon as one adds only one (empty) Objective-c class to the target (the .m file) `pluginDidLoad` is not getting called anymore.

**Comment by kattrali** [comment] 2015-03-10 16:54
Thanks for the report! I think this is probably a duplicate of #31.

**Comment by benrudhart** [comment] 2015-03-10 19:30
Well it's definitely similar to the one in #31. But the special case here is that it is possible to add (many) Swift files and the plugin works just fine. It's just not working, when Swift gets mixed with Objective-C.
I was able to get in running by starting out with an Objective-C plugin and adding swift files -> the plugin file containing the `pluginDidLoad` has to be Objective-C the other files may be in Swift. I hope this is a beta issue and will be fixed in the final Xcode 6.3...

**Comment by kattrali** [comment] 2015-03-10 21:47
Very weird. I may have misunderstood. Fingers crossed for some clarity in 6.3. :grin:

**Comment by DerekK19** [comment] 2015-04-11 03:55
Looks like it's not fixed in 6.3. My Xcode plugin has an Obj-C helpper class that gets the current project name - nothing more. I remove that class from the project and remove the call to it and my plugin loads.

That said, the plugin loads and does some stuff, including adding a menu item. That all looks OK, the system log looks fine, but then Xcode hangs. I delete my plugin from my Plug-ins folder and Xcode runs OK.

Looks like plugins act differently under Xcode 6.3

**Comment by mgee** [comment] 2015-04-11 06:57
I once experience the problem that my plugin didn't load and it was because of the ordering of the files in the compile sources build phase.
After changing the order so that the file containing the `pluginDidLoad` function was compiled first, it worked.

Maybe that does work in you case too.

**Comment by DerekK19** [comment] 2015-04-13 06:10
Thanks for the suggestion @mgee. No luck however. I am persevering though, there must be a simple explanation. Or I can put my Objective-C hat on and go all old-school. Not the end of the world, since this is a new project I'm working on

**Comment by benrudhart** [comment] 2015-04-13 06:35
Your suggestion sounds great @mgee. Do you have a working example for that?

**Comment by mgee** [comment] 2015-04-13 16:57
@benrudhart sadly not. The project I am working on is not publicly available.

**Comment by kattrali** [comment] 2015-05-20 18:55
Closed by #35

**Closed by kattrali** 2015-05-20 18:55 UTC
